# fly.toml app configuration file generated for googleauth-black-field-767 on 2025-03-11T19:03:10+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'googleauth-black-field-767'
primary_region = 'sea'
[deploy]
  release_command = "rake db:migrate"

[build]

[http_service]
  internal_port = 4567
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
